MYSQL_USERNAME: root
MYSQL_PASSWORD: Switch@906
MYSQL_HOST:  jdbc:mysql://localhost:3306/investrust_management?createDatabaseIfNotExist=true
#MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_DB: investrust_management

#Server
SERVER_PORT: 7000
ACTIVE_PROFILE: dev