version: '3.8'

services:
  mysql:
    container_name: MySQL
    image: mysql/mysql-server
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Switch@906
      MYSQL_DATA_DIR: /data/mysql
    volumes:
      - mysql:/data/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql
    restart: unless-stopped
networks:
  mysql:
    driver: bridge

volumes:
  mysql:
    driver: local
