eureka:
  client:
    register-with-eureka: false
server:
  port: 8770
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: trustmonie
          uri: http://localhost:9000
          predicates:
            - Path=/api/v1/users/**
        - id: email
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/email/**
        - id: investrust
          uri: http://localhost:7000
          predicates:
            - Path=/api/v1/investrust/**
