spring:
#  config:
#    import: optional:configserver:http://localhost:8761

  #  profiles:
#    active: ${ACTIVE_PROFILE:dev}

  datasource:
    url: jdbc:mysql://localhost:3306/tranxactrust_management?createDatabaseIfNotExist=true
    username: root
    password: Switch@906
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: ${SERVER_PORT:8080}