MYSQL_USERNAME: root
MYSQL_PASSWORD: Switch@906
MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_DB: trustmonie_management

#Server
SERVER_PORT: 9090
ACTIVE_PROFILE: prod

Email_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ADDRESS: harrynwa90@gmail.com
EMAIL_PASSWORD: yyof ploj giup hfwi
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
