MYSQL_USERNAME: root
MYSQL_PASSWORD: Switch@906
MYSQL_HOST:  jdbc:mysql://localhost:3306/trustmonie_management?createDatabaseIfNotExist=true
#MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_DB: trustmonie_management

#Server
SERVER_PORT: 9000
ACTIVE_PROFILE: dev

Email_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ADDRESS: nwaogwugwuharrison@gmail.com
EMAIL_PASSWORD: qrjz pijj hapk lqye
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT:8070}
